services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

