name: "Linting"
on: [push]
jobs:
    pyflakes:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install pyflakes
              run: pip install pyflakes
            - name: Run Pyflakes
              run: pyflakes .