name: "Unit Tests"
on: [push]
jobs:
    Tests:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install pytest
              run: pip install pytest
            - name: Install requirements
              run: pip install -r requirements.txt
            - name: Root tests
              run: pytest $(find . -maxdepth 1 -name "test_*.py")
            - name: Direct exchange tests
              run: cd hello-world & pytest